# Jekyll workshop template
# based on minima theme https://github.com/jekyll/minima

# Site settings

title: Make @ the MILL!
description: > 
  Learn about the Arduino electronics platform by making lights blink and buzzers buzz! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uidaholib.github.io/make-at-the-mill" # the base hostname & protocol for your site

google_analytics: UA-74844011-1

# Build settings
markdown: kramdown

# note: fig include, {% include image.html file="my-cat.jpg" alt="cat" cap="My cat" %}
